### ISSUE TITLE
App crashes while writing code

### ISSUE THREAD

**Issue by bassem-saeed** [Deenu143/CodeAssist-ALPHA-0.2.9#3]
When I was writing a kotlin code in my ViewPager adapter class the app carshed, see the error:

Build version: 0.2.9-alpha02 
Build date: 1981-01-01 01:01:02 
Current date: 2023-02-23 14:21:32 
Device: Samsung SM-A022F 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 45, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.updateLineDisplayList(EditorPainter.java:268)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:127)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:1014)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
	at android.view.View.updateDisplayListIfDirty(View.java:22731)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
	at android.view.View.updateDisplayListIfDirty(View.java:22731)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
	at android.view.View.updateDisplayListIfDirty(View.java:22731)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
	at android.view.View.updateDisplayListIfDirty(View.java:22731)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1483)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.draw(View.java:23904)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2023-02-23 14:14:05: MainActivity created
2023-02-23 14:14:05: MainActivity resumed
2023-02-23 14:14:07: MainActivity paused
2023-02-23 14:14:07: SettingsActivity created
2023-02-23 14:14:07: SettingsActivity resumed
2023-02-23 14:14:24: SettingsActivity paused
2023-02-23 14:14:24: MainActivity resumed
2023-02-23 14:14:25: SettingsActivity destroyed

**Comment by Deenu143** [comment]
It will be fixed when latest Sora editor library implemented
